base: /
dependencies:
  - typo3/fluid-styled-content
  - typo3/fluid-styled-content-css
  - workshop/site-package
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: 'I love coffee'
